// Auto-generated by: pnpm supabase gen types typescript --project-id <ref> --schema public
// Re-generate this file whenever the schema changes.
// Until the Supabase project is linked, this is a minimal placeholder.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: "traveler" | "guide" | "admin";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["users"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
      };
      regions: {
        Row: {
          id: string;
          name: string;
          slug: string;
          country: string;
          description: string | null;
          hero_image_url: string | null;
          best_season: string | null;
          sustainability_note: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["regions"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["regions"]["Insert"]>;
      };
      guide_profiles: {
        Row: {
          id: string;
          user_id: string | null;
          display_name: string;
          slug: string;
          bio: string | null;
          location: string | null;
          region_id: string | null;
          profile_photo_url: string | null;
          years_experience: number | null;
          languages: string[];
          specialties: string[];
          certifications: string | null;
          license_files: string[];
          verification_status: "draft" | "submitted" | "verified" | "rejected" | "suspended";
          is_featured: boolean;
          price_per_person: number | null;
          price_per_vehicle: number | null;
          vehicle_capacity: number | null;
          transport_options: string[];
          certification_types: string[];
          suitable_for: string[];
          local_origin: string | null;
          sustainability_tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["guide_profiles"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["guide_profiles"]["Insert"]>;
      };
      trips: {
        Row: {
          id: string;
          guide_id: string;
          region_id: string | null;
          title: string;
          slug: string;
          short_description: string | null;
          full_description: string | null;
          duration_days: number;
          base_price: number;
          currency: string;
          max_group_size: number | null;
          min_group_size: number;
          activity_type: "safari" | "wildlife" | "hiking" | "cultural" | "water" | "photography" | "birdwatching" | "multi-activity" | null;
          difficulty: "easy" | "moderate" | "challenging" | "extreme" | null;
          included: string[];
          not_included: string[];
          safety_notes: string | null;
          itinerary: Json;
          gallery_urls: string[];
          status: "draft" | "submitted" | "published" | "rejected" | "archived";
          is_featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["trips"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["trips"]["Insert"]>;
      };
      availability_blocks: {
        Row: {
          id: string;
          guide_id: string;
          start_date: string;
          end_date: string;
          status: "available" | "unavailable";
          note: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["availability_blocks"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["availability_blocks"]["Insert"]>;
      };
      booking_requests: {
        Row: {
          id: string;
          trip_id: string | null;
          guide_id: string;
          traveler_name: string;
          traveler_email: string;
          traveler_phone: string | null;
          preferred_start_date: string;
          preferred_end_date: string | null;
          travelers_count: number;
          message: string | null;
          estimated_value: number | null;
          currency: string;
          status: "pending" | "accepted" | "declined" | "canceled" | "completed";
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["booking_requests"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["booking_requests"]["Insert"]>;
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          reason: string;
          message: string;
          status: "new" | "read" | "archived";
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["contact_messages"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["contact_messages"]["Insert"]>;
      };
      media_assets: {
        Row: {
          id: string;
          owner_user_id: string | null;
          url: string;
          type: "image" | "document" | null;
          alt_text: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["media_assets"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["media_assets"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

// Convenience row types
export type User = Database["public"]["Tables"]["users"]["Row"];
export type Region = Database["public"]["Tables"]["regions"]["Row"];
export type GuideProfile = Database["public"]["Tables"]["guide_profiles"]["Row"];
export type Trip = Database["public"]["Tables"]["trips"]["Row"];
export type AvailabilityBlock = Database["public"]["Tables"]["availability_blocks"]["Row"];
export type BookingRequest = Database["public"]["Tables"]["booking_requests"]["Row"];
export type ContactMessage = Database["public"]["Tables"]["contact_messages"]["Row"];
export type MediaAsset = Database["public"]["Tables"]["media_assets"]["Row"];
